name: plant_care
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.1.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  sqflite: ^2.0.0
  path: ^1.8.0
  win32: ^5.12.0           # keep your 5.x constraint
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.0.0
  share_plus: ^11.0.0      # bump into the v11 series
  timeago: ^3.3.0

  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.4.0
  font_awesome_flutter: ^10.8.0
  page_transition: ^2.2.1

  image_picker: ^1.1.2
  http: ^0.13.6
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/images/ss.png
    - assets/images/banner_description.jpg
    - assets/images/banner_diseases.jpg
    - assets/images/banner_care.jpg

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
